name: linux-integration-testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: build MSVC release
        run: |
          bash cmake --build . --config Release