name: linux-integration-testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: build clang release
        run: |
          bash cmake --build . --config Release
          bash ./.ci/run-programs.sh
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
